/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gabriel.formularios;

/**
 *
 * @author SATC
 */
public class Paciente extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Paciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCadastroPaciente = new javax.swing.JPanel();
        jLIDPaciente = new javax.swing.JLabel();
        jLNumeroSUSPaciente = new javax.swing.JLabel();
        jLResponsavelPaciente = new javax.swing.JLabel();
        jLNomePaciente = new javax.swing.JLabel();
        jLCPFPaciente = new javax.swing.JLabel();
        jLRGPaciente = new javax.swing.JLabel();
        jLEnderecoPaciente = new javax.swing.JLabel();
        jLTelefonePaciente = new javax.swing.JLabel();
        jLEstadoCivilPaciente = new javax.swing.JLabel();
        jLDatadeNascimentoPaciente = new javax.swing.JLabel();
        jLSexoPaciente = new javax.swing.JLabel();
        jTFIDPaciente = new javax.swing.JTextField();
        jTFNumeroSUSPaciente = new javax.swing.JTextField();
        jTFResponsavelPaciente = new javax.swing.JTextField();
        jTFNomePaciente = new javax.swing.JTextField();
        jTFCPFPaciente = new javax.swing.JTextField();
        jTFRGPaciente = new javax.swing.JTextField();
        jTFEnderecoPaciente = new javax.swing.JTextField();
        jTFTelefonePaciente = new javax.swing.JTextField();
        jTFEstadoCivilPaciente = new javax.swing.JTextField();
        jTFDatadeNascimentoPaciente = new javax.swing.JTextField();
        jTFSexoPaciente = new javax.swing.JTextField();
        jBCadastrarPaciente = new javax.swing.JButton();
        jLCadastrodoPaciente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPCadastroPaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLIDPaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLIDPaciente.setText("ID do Paciente:");

        jLNumeroSUSPaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLNumeroSUSPaciente.setText("Número do SUS:");

        jLResponsavelPaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLResponsavelPaciente.setText("Responsável:");

        jLNomePaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLNomePaciente.setText("Nome:");

        jLCPFPaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLCPFPaciente.setText("CPF:");

        jLRGPaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLRGPaciente.setText("RG:");

        jLEnderecoPaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLEnderecoPaciente.setText("Endereço:");

        jLTelefonePaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLTelefonePaciente.setText("Telefone:");

        jLEstadoCivilPaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLEstadoCivilPaciente.setText("Estado Civil:");

        jLDatadeNascimentoPaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLDatadeNascimentoPaciente.setText("Data de Nascimento:");

        jLSexoPaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLSexoPaciente.setText("Sexo:");

        jTFIDPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFNumeroSUSPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFResponsavelPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFNomePaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFCPFPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFRGPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFEnderecoPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFTelefonePaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFEstadoCivilPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFDatadeNascimentoPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFSexoPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jBCadastrarPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBCadastrarPaciente.setText("Cadastrar");

        javax.swing.GroupLayout jPCadastroPacienteLayout = new javax.swing.GroupLayout(jPCadastroPaciente);
        jPCadastroPaciente.setLayout(jPCadastroPacienteLayout);
        jPCadastroPacienteLayout.setHorizontalGroup(
            jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroPacienteLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNumeroSUSPaciente)
                    .addComponent(jLResponsavelPaciente)
                    .addComponent(jLNomePaciente)
                    .addComponent(jLCPFPaciente)
                    .addComponent(jLIDPaciente)
                    .addComponent(jLRGPaciente))
                .addGap(27, 27, 27)
                .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFCPFPaciente)
                    .addComponent(jTFIDPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jTFNumeroSUSPaciente)
                    .addComponent(jTFResponsavelPaciente)
                    .addComponent(jTFNomePaciente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFRGPaciente))
                .addGap(31, 31, 31)
                .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLDatadeNascimentoPaciente)
                    .addComponent(jLSexoPaciente)
                    .addComponent(jLEnderecoPaciente)
                    .addComponent(jLTelefonePaciente)
                    .addComponent(jLEstadoCivilPaciente))
                .addGap(18, 18, 18)
                .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFEstadoCivilPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jTFSexoPaciente)
                    .addComponent(jTFEnderecoPaciente)
                    .addComponent(jTFTelefonePaciente)
                    .addComponent(jTFDatadeNascimentoPaciente))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroPacienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCadastrarPaciente)
                .addContainerGap())
        );
        jPCadastroPacienteLayout.setVerticalGroup(
            jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroPacienteLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPCadastroPacienteLayout.createSequentialGroup()
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEnderecoPaciente)
                            .addComponent(jTFEnderecoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLTelefonePaciente)
                            .addComponent(jTFTelefonePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEstadoCivilPaciente)
                            .addComponent(jTFEstadoCivilPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDatadeNascimentoPaciente)
                            .addComponent(jTFDatadeNascimentoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLSexoPaciente)
                            .addComponent(jTFSexoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPCadastroPacienteLayout.createSequentialGroup()
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLIDPaciente)
                            .addComponent(jTFIDPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNumeroSUSPaciente)
                            .addComponent(jTFNumeroSUSPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLResponsavelPaciente)
                            .addComponent(jTFResponsavelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNomePaciente)
                            .addComponent(jTFNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCPFPaciente)
                            .addComponent(jTFCPFPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLRGPaciente)
                    .addComponent(jTFRGPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCadastrarPaciente)
                .addContainerGap())
        );

        jLCadastrodoPaciente.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLCadastrodoPaciente.setText("Cadastro do Paciente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPCadastroPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLCadastrodoPaciente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCadastrodoPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPCadastroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrarPaciente;
    private javax.swing.JLabel jLCPFPaciente;
    private javax.swing.JLabel jLCadastrodoPaciente;
    private javax.swing.JLabel jLDatadeNascimentoPaciente;
    private javax.swing.JLabel jLEnderecoPaciente;
    private javax.swing.JLabel jLEstadoCivilPaciente;
    private javax.swing.JLabel jLIDPaciente;
    private javax.swing.JLabel jLNomePaciente;
    private javax.swing.JLabel jLNumeroSUSPaciente;
    private javax.swing.JLabel jLRGPaciente;
    private javax.swing.JLabel jLResponsavelPaciente;
    private javax.swing.JLabel jLSexoPaciente;
    private javax.swing.JLabel jLTelefonePaciente;
    private javax.swing.JPanel jPCadastroPaciente;
    private javax.swing.JTextField jTFCPFPaciente;
    private javax.swing.JTextField jTFDatadeNascimentoPaciente;
    private javax.swing.JTextField jTFEnderecoPaciente;
    private javax.swing.JTextField jTFEstadoCivilPaciente;
    private javax.swing.JTextField jTFIDPaciente;
    private javax.swing.JTextField jTFNomePaciente;
    private javax.swing.JTextField jTFNumeroSUSPaciente;
    private javax.swing.JTextField jTFRGPaciente;
    private javax.swing.JTextField jTFResponsavelPaciente;
    private javax.swing.JTextField jTFSexoPaciente;
    private javax.swing.JTextField jTFTelefonePaciente;
    // End of variables declaration//GEN-END:variables
}
