/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gabriel.interfaces;

import br.com.gabriel.objetos.Enfermeira;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author SATC
 */
public class JFEnfermeira extends javax.swing.JFrame {

    /**
     * Creates new form Enfermeira
     */
    public JFEnfermeira() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCadastrodeEnfermeira = new javax.swing.JLabel();
        jPCadastroEnfermeira = new javax.swing.JPanel();
        jLCofenEnfermeira = new javax.swing.JLabel();
        jLSetorEnfermeira = new javax.swing.JLabel();
        jLNomeEnfermeira = new javax.swing.JLabel();
        jLCPFEnfermeira = new javax.swing.JLabel();
        jLRGEnfermeira = new javax.swing.JLabel();
        jLEnderecoEnfermeira = new javax.swing.JLabel();
        jLTelefoneEnfermeira = new javax.swing.JLabel();
        jLEstadoCivilEnfermeira = new javax.swing.JLabel();
        jLDatadeNascimentoEnfermeira = new javax.swing.JLabel();
        jLSexoEnfermeira = new javax.swing.JLabel();
        jTFCofenEnfermeira = new javax.swing.JTextField();
        jTFSetorEnfermeira = new javax.swing.JTextField();
        jTFNomeEnfermeira = new javax.swing.JTextField();
        jTFCPFEnfermeira = new javax.swing.JTextField();
        jTFRGEnfermeira = new javax.swing.JTextField();
        jTFEnderecoEnfermeira = new javax.swing.JTextField();
        jTFTelefoneEnfermeira = new javax.swing.JTextField();
        jTFEstadoCivilEnfermeira = new javax.swing.JTextField();
        jTFDatadeNascimentoEnfermeira = new javax.swing.JTextField();
        jTFSexoEnfermeira = new javax.swing.JTextField();
        jBCadastrarEnfermeira = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLCadastrodeEnfermeira.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLCadastrodeEnfermeira.setText("Cadastro de Enfermeira(o)");

        jPCadastroEnfermeira.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLCofenEnfermeira.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLCofenEnfermeira.setText("Cofen:");

        jLSetorEnfermeira.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLSetorEnfermeira.setText("Setor:");

        jLNomeEnfermeira.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLNomeEnfermeira.setText("Nome:");

        jLCPFEnfermeira.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLCPFEnfermeira.setText("CPF:");

        jLRGEnfermeira.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLRGEnfermeira.setText("RG:");

        jLEnderecoEnfermeira.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLEnderecoEnfermeira.setText("Endereço:");

        jLTelefoneEnfermeira.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLTelefoneEnfermeira.setText("Telefone:");

        jLEstadoCivilEnfermeira.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLEstadoCivilEnfermeira.setText("Estado Civil:");

        jLDatadeNascimentoEnfermeira.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLDatadeNascimentoEnfermeira.setText("Data de Nascimento:");

        jLSexoEnfermeira.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLSexoEnfermeira.setText("Sexo:");

        jTFCofenEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFSetorEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFNomeEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFCPFEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFRGEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFEnderecoEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFTelefoneEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFEstadoCivilEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFDatadeNascimentoEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFSexoEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jBCadastrarEnfermeira.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBCadastrarEnfermeira.setText("Cadastrar");
        jBCadastrarEnfermeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarEnfermeiraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCadastroEnfermeiraLayout = new javax.swing.GroupLayout(jPCadastroEnfermeira);
        jPCadastroEnfermeira.setLayout(jPCadastroEnfermeiraLayout);
        jPCadastroEnfermeiraLayout.setHorizontalGroup(
            jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroEnfermeiraLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLSetorEnfermeira)
                    .addComponent(jLNomeEnfermeira)
                    .addComponent(jLCPFEnfermeira)
                    .addComponent(jLCofenEnfermeira)
                    .addComponent(jLRGEnfermeira))
                .addGap(86, 86, 86)
                .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFCPFEnfermeira, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(jTFCofenEnfermeira, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFSetorEnfermeira)
                    .addComponent(jTFNomeEnfermeira, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFRGEnfermeira))
                .addGap(29, 29, 29)
                .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLDatadeNascimentoEnfermeira)
                    .addComponent(jLSexoEnfermeira)
                    .addComponent(jLEnderecoEnfermeira)
                    .addComponent(jLTelefoneEnfermeira)
                    .addComponent(jLEstadoCivilEnfermeira))
                .addGap(18, 18, 18)
                .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFEstadoCivilEnfermeira, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(jTFSexoEnfermeira)
                    .addComponent(jTFTelefoneEnfermeira)
                    .addComponent(jTFDatadeNascimentoEnfermeira)
                    .addComponent(jTFEnderecoEnfermeira, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroEnfermeiraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCadastrarEnfermeira)
                .addContainerGap())
        );
        jPCadastroEnfermeiraLayout.setVerticalGroup(
            jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroEnfermeiraLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPCadastroEnfermeiraLayout.createSequentialGroup()
                        .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEnderecoEnfermeira)
                            .addComponent(jTFEnderecoEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLTelefoneEnfermeira)
                            .addComponent(jTFTelefoneEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEstadoCivilEnfermeira)
                            .addComponent(jTFEstadoCivilEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDatadeNascimentoEnfermeira)
                            .addComponent(jTFDatadeNascimentoEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLSexoEnfermeira)
                            .addComponent(jTFSexoEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPCadastroEnfermeiraLayout.createSequentialGroup()
                        .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCofenEnfermeira)
                            .addComponent(jTFCofenEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLSetorEnfermeira)
                            .addComponent(jTFSetorEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNomeEnfermeira)
                            .addComponent(jTFNomeEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCPFEnfermeira)
                            .addComponent(jTFCPFEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLRGEnfermeira)
                            .addComponent(jTFRGEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jBCadastrarEnfermeira)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPCadastroEnfermeira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLCadastrodeEnfermeira)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLCadastrodeEnfermeira)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPCadastroEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarEnfermeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarEnfermeiraActionPerformed
        Enfermeira e;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String NomeEnfermeira = this.jTFNomeEnfermeira.getText();
        try {
            Date DataNascimentoEnfermeira = sdf.parse(this.jTFDatadeNascimentoEnfermeira.getText());
        } catch (ParseException ex) {
            Logger.getLogger(JFEnfermeira.class.getName()).log(Level.SEVERE, null, ex);
        }
        String CPFEnfermeira = this.jTFCPFEnfermeira.getText();
        String RGEnfermeira = this.jTFRGEnfermeira.getText();
        String EnderecoEnfermeira = this.jTFEnderecoEnfermeira.getText();
        String TelefoneEnfermeira = this.jTFTelefoneEnfermeira.getText();
        String EstadoCivilEnfermeira = this.jTFEstadoCivilEnfermeira.getText();
        char SexoEnfermeira = this.jTFSexoEnfermeira.getText().toUpperCase().charAt(0);
        int Cofen = Integer.parseInt(this.jTFCofenEnfermeira.getText());
        String SetorEnfermeira = this.jTFSetorEnfermeira.getText();
    }//GEN-LAST:event_jBCadastrarEnfermeiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFEnfermeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFEnfermeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFEnfermeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFEnfermeira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFEnfermeira().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrarEnfermeira;
    private javax.swing.JLabel jLCPFEnfermeira;
    private javax.swing.JLabel jLCadastrodeEnfermeira;
    private javax.swing.JLabel jLCofenEnfermeira;
    private javax.swing.JLabel jLDatadeNascimentoEnfermeira;
    private javax.swing.JLabel jLEnderecoEnfermeira;
    private javax.swing.JLabel jLEstadoCivilEnfermeira;
    private javax.swing.JLabel jLNomeEnfermeira;
    private javax.swing.JLabel jLRGEnfermeira;
    private javax.swing.JLabel jLSetorEnfermeira;
    private javax.swing.JLabel jLSexoEnfermeira;
    private javax.swing.JLabel jLTelefoneEnfermeira;
    private javax.swing.JPanel jPCadastroEnfermeira;
    private javax.swing.JTextField jTFCPFEnfermeira;
    private javax.swing.JTextField jTFCofenEnfermeira;
    private javax.swing.JTextField jTFDatadeNascimentoEnfermeira;
    private javax.swing.JTextField jTFEnderecoEnfermeira;
    private javax.swing.JTextField jTFEstadoCivilEnfermeira;
    private javax.swing.JTextField jTFNomeEnfermeira;
    private javax.swing.JTextField jTFRGEnfermeira;
    private javax.swing.JTextField jTFSetorEnfermeira;
    private javax.swing.JTextField jTFSexoEnfermeira;
    private javax.swing.JTextField jTFTelefoneEnfermeira;
    // End of variables declaration//GEN-END:variables
}
