/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gabriel.interfaces;

import br.com.gabriel.objetos.Medico;
import br.com.gabriel.singleton.SMedico;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author SATC
 */
public class JFMedico extends javax.swing.JFrame {

    Medico m;

    /**
     * Creates new form Medico
     */
    public JFMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCadastrodeMedico = new javax.swing.JLabel();
        jPCadastroMedico = new javax.swing.JPanel();
        jLCRMMedico = new javax.swing.JLabel();
        jLEspecialidadeMedico = new javax.swing.JLabel();
        jLSetorMedico = new javax.swing.JLabel();
        jLNomeMedico = new javax.swing.JLabel();
        jLCPFMedico = new javax.swing.JLabel();
        jLRGMedico = new javax.swing.JLabel();
        jLEnderecoMedico = new javax.swing.JLabel();
        jLTelefoneMedico = new javax.swing.JLabel();
        jLEstadoCivilMedico = new javax.swing.JLabel();
        jLDatadeNascimentoMedico = new javax.swing.JLabel();
        jLSexoMedico = new javax.swing.JLabel();
        jTFCRMMedico = new javax.swing.JTextField();
        jTFEspecialidadeMedico = new javax.swing.JTextField();
        jTFSetorMedico = new javax.swing.JTextField();
        jTFNomeMedico = new javax.swing.JTextField();
        jTFCPFMedico = new javax.swing.JTextField();
        jTFRGMedico = new javax.swing.JTextField();
        jTFEnderecoMedico = new javax.swing.JTextField();
        jTFTelefoneMedico = new javax.swing.JTextField();
        jTFEstadoCivilMedico = new javax.swing.JTextField();
        jTFDatadeNascimentoMedico = new javax.swing.JTextField();
        jTFSexoMedico = new javax.swing.JTextField();
        jBCadastrarMedico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLCadastrodeMedico.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLCadastrodeMedico.setText("Cadastro de Médico");

        jPCadastroMedico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLCRMMedico.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLCRMMedico.setText("CRM:");

        jLEspecialidadeMedico.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLEspecialidadeMedico.setText("Especialidade:");

        jLSetorMedico.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLSetorMedico.setText("Setor:");

        jLNomeMedico.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLNomeMedico.setText("Nome:");

        jLCPFMedico.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLCPFMedico.setText("CPF:");

        jLRGMedico.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLRGMedico.setText("RG:");

        jLEnderecoMedico.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLEnderecoMedico.setText("Endereço:");

        jLTelefoneMedico.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLTelefoneMedico.setText("Telefone:");

        jLEstadoCivilMedico.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLEstadoCivilMedico.setText("Estado Civil:");

        jLDatadeNascimentoMedico.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLDatadeNascimentoMedico.setText("Data de Nascimento:");

        jLSexoMedico.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLSexoMedico.setText("Sexo:");

        jTFCRMMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFEspecialidadeMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFSetorMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFNomeMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFCPFMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFRGMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFEnderecoMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFTelefoneMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFEstadoCivilMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFDatadeNascimentoMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFSexoMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jBCadastrarMedico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBCadastrarMedico.setText("Cadastrar");
        jBCadastrarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarMedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCadastroMedicoLayout = new javax.swing.GroupLayout(jPCadastroMedico);
        jPCadastroMedico.setLayout(jPCadastroMedicoLayout);
        jPCadastroMedicoLayout.setHorizontalGroup(
            jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroMedicoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLEspecialidadeMedico)
                    .addComponent(jLSetorMedico)
                    .addComponent(jLNomeMedico)
                    .addComponent(jLCPFMedico)
                    .addComponent(jLCRMMedico)
                    .addComponent(jLRGMedico))
                .addGap(27, 27, 27)
                .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFCPFMedico)
                    .addComponent(jTFCRMMedico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jTFEspecialidadeMedico)
                    .addComponent(jTFSetorMedico)
                    .addComponent(jTFNomeMedico, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFRGMedico))
                .addGap(29, 29, 29)
                .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLDatadeNascimentoMedico)
                    .addComponent(jLSexoMedico)
                    .addComponent(jLEnderecoMedico)
                    .addComponent(jLTelefoneMedico)
                    .addComponent(jLEstadoCivilMedico))
                .addGap(18, 18, 18)
                .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFEstadoCivilMedico, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(jTFSexoMedico)
                    .addComponent(jTFTelefoneMedico)
                    .addComponent(jTFDatadeNascimentoMedico)
                    .addComponent(jTFEnderecoMedico, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroMedicoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCadastrarMedico)
                .addContainerGap())
        );
        jPCadastroMedicoLayout.setVerticalGroup(
            jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroMedicoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPCadastroMedicoLayout.createSequentialGroup()
                        .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEnderecoMedico)
                            .addComponent(jTFEnderecoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLTelefoneMedico)
                            .addComponent(jTFTelefoneMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEstadoCivilMedico)
                            .addComponent(jTFEstadoCivilMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDatadeNascimentoMedico)
                            .addComponent(jTFDatadeNascimentoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLSexoMedico)
                            .addComponent(jTFSexoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPCadastroMedicoLayout.createSequentialGroup()
                        .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCRMMedico)
                            .addComponent(jTFCRMMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEspecialidadeMedico)
                            .addComponent(jTFEspecialidadeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLSetorMedico)
                            .addComponent(jTFSetorMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNomeMedico)
                            .addComponent(jTFNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCPFMedico)
                            .addComponent(jTFCPFMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPCadastroMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLRGMedico)
                    .addComponent(jTFRGMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCadastrarMedico)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPCadastroMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLCadastrodeMedico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCadastrodeMedico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPCadastroMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarMedicoActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String NomeMedico = this.jTFNomeMedico.getText();
        Date DataNascimentoMedico = new Date();
        try {
            DataNascimentoMedico = sdf.parse(this.jTFDatadeNascimentoMedico.getText());
        } catch (ParseException ex) {
            Logger.getLogger(JFMedico.class.getName()).log(Level.SEVERE, null, ex);
        }
        String CPFMedico = this.jTFCPFMedico.getText();
        String RGMedico = this.jTFRGMedico.getText();
        String EnderecoMedico = this.jTFEnderecoMedico.getText();
        String TelefoneMedico = this.jTFTelefoneMedico.getText();
        String EstadoCivilMedico = this.jTFEstadoCivilMedico.getText();
        char SexoMedico = this.jTFSexoMedico.getText().toUpperCase().charAt(0);
        int CRM = Integer.parseInt(this.jTFCRMMedico.getText());
        String Especialidade = this.jTFEspecialidadeMedico.getText();
        String SetorMedico = this.jTFSetorMedico.getText();
        m = new Medico(CRM, Especialidade, SetorMedico, RGMedico, CPFMedico, RGMedico, RGMedico, TelefoneMedico, EstadoCivilMedico, DataNascimentoMedico, SexoMedico);
        SMedico.getInstance().getMedicos().add(m);
    }//GEN-LAST:event_jBCadastrarMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrarMedico;
    private javax.swing.JLabel jLCPFMedico;
    private javax.swing.JLabel jLCRMMedico;
    private javax.swing.JLabel jLCadastrodeMedico;
    private javax.swing.JLabel jLDatadeNascimentoMedico;
    private javax.swing.JLabel jLEnderecoMedico;
    private javax.swing.JLabel jLEspecialidadeMedico;
    private javax.swing.JLabel jLEstadoCivilMedico;
    private javax.swing.JLabel jLNomeMedico;
    private javax.swing.JLabel jLRGMedico;
    private javax.swing.JLabel jLSetorMedico;
    private javax.swing.JLabel jLSexoMedico;
    private javax.swing.JLabel jLTelefoneMedico;
    private javax.swing.JPanel jPCadastroMedico;
    private javax.swing.JTextField jTFCPFMedico;
    private javax.swing.JTextField jTFCRMMedico;
    private javax.swing.JTextField jTFDatadeNascimentoMedico;
    private javax.swing.JTextField jTFEnderecoMedico;
    private javax.swing.JTextField jTFEspecialidadeMedico;
    private javax.swing.JTextField jTFEstadoCivilMedico;
    private javax.swing.JTextField jTFNomeMedico;
    private javax.swing.JTextField jTFRGMedico;
    private javax.swing.JTextField jTFSetorMedico;
    private javax.swing.JTextField jTFSexoMedico;
    private javax.swing.JTextField jTFTelefoneMedico;
    // End of variables declaration//GEN-END:variables
}
