/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gabriel.interfaces;

import br.com.gabriel.objetos.Paciente;
import br.com.gabriel.singleton.SPaciente;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SATC
 */
public class JFPaciente extends javax.swing.JFrame {

    Paciente p;

    /**
     * Creates new form Cadastro
     */
    public JFPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPCadastroPaciente = new javax.swing.JPanel();
        jLIDPaciente = new javax.swing.JLabel();
        jLNumeroSUSPaciente = new javax.swing.JLabel();
        jLResponsavelPaciente = new javax.swing.JLabel();
        jLNomePaciente = new javax.swing.JLabel();
        jLCPFPaciente = new javax.swing.JLabel();
        jLRGPaciente = new javax.swing.JLabel();
        jLEnderecoPaciente = new javax.swing.JLabel();
        jLTelefonePaciente = new javax.swing.JLabel();
        jLEstadoCivilPaciente = new javax.swing.JLabel();
        jLDatadeNascimentoPaciente = new javax.swing.JLabel();
        jLSexoPaciente = new javax.swing.JLabel();
        jTFIDPaciente = new javax.swing.JTextField();
        jTFNumeroSUSPaciente = new javax.swing.JTextField();
        jTFResponsavelPaciente = new javax.swing.JTextField();
        jTFNomePaciente = new javax.swing.JTextField();
        jTFCPFPaciente = new javax.swing.JTextField();
        jTFRGPaciente = new javax.swing.JTextField();
        jTFEnderecoPaciente = new javax.swing.JTextField();
        jTFTelefonePaciente = new javax.swing.JTextField();
        jTFEstadoCivilPaciente = new javax.swing.JTextField();
        jTFDatadeNascimentoPaciente = new javax.swing.JTextField();
        jTFSexoPaciente = new javax.swing.JTextField();
        jBCadastrarPaciente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLCadastrodoPaciente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPCadastroPaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLIDPaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLIDPaciente.setText("ID do Paciente:");

        jLNumeroSUSPaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLNumeroSUSPaciente.setText("Número do SUS:");

        jLResponsavelPaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLResponsavelPaciente.setText("Responsável:");

        jLNomePaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLNomePaciente.setText("Nome:");

        jLCPFPaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLCPFPaciente.setText("CPF:");

        jLRGPaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLRGPaciente.setText("RG:");

        jLEnderecoPaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLEnderecoPaciente.setText("Endereço:");

        jLTelefonePaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLTelefonePaciente.setText("Telefone:");

        jLEstadoCivilPaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLEstadoCivilPaciente.setText("Estado Civil:");

        jLDatadeNascimentoPaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLDatadeNascimentoPaciente.setText("Data de Nascimento:");

        jLSexoPaciente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLSexoPaciente.setText("Sexo: M ou F");

        jTFIDPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFNumeroSUSPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFResponsavelPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFNomePaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFCPFPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFRGPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFEnderecoPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFTelefonePaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFEstadoCivilPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFDatadeNascimentoPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jTFSexoPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jBCadastrarPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBCadastrarPaciente.setText("Cadastrar");
        jBCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarPacienteActionPerformed(evt);
            }
        });

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCadastroPacienteLayout = new javax.swing.GroupLayout(jPCadastroPaciente);
        jPCadastroPaciente.setLayout(jPCadastroPacienteLayout);
        jPCadastroPacienteLayout.setHorizontalGroup(
            jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroPacienteLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNumeroSUSPaciente)
                    .addComponent(jLResponsavelPaciente)
                    .addComponent(jLNomePaciente)
                    .addComponent(jLCPFPaciente)
                    .addComponent(jLIDPaciente)
                    .addComponent(jLRGPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFResponsavelPaciente)
                    .addComponent(jTFNumeroSUSPaciente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFRGPaciente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFNomePaciente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFCPFPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jTFIDPaciente))
                .addGap(31, 31, 31)
                .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLDatadeNascimentoPaciente)
                    .addComponent(jLSexoPaciente)
                    .addComponent(jLEnderecoPaciente)
                    .addComponent(jLTelefonePaciente)
                    .addComponent(jLEstadoCivilPaciente))
                .addGap(18, 18, 18)
                .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFEstadoCivilPaciente)
                    .addComponent(jTFSexoPaciente)
                    .addComponent(jTFEnderecoPaciente)
                    .addComponent(jTFTelefonePaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jTFDatadeNascimentoPaciente))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroPacienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(32, 32, 32)
                .addComponent(jBCadastrarPaciente)
                .addContainerGap())
        );
        jPCadastroPacienteLayout.setVerticalGroup(
            jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroPacienteLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPCadastroPacienteLayout.createSequentialGroup()
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEnderecoPaciente)
                            .addComponent(jTFEnderecoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLTelefonePaciente)
                            .addComponent(jTFTelefonePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEstadoCivilPaciente)
                            .addComponent(jTFEstadoCivilPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDatadeNascimentoPaciente)
                            .addComponent(jTFDatadeNascimentoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLSexoPaciente)
                            .addComponent(jTFSexoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPCadastroPacienteLayout.createSequentialGroup()
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLIDPaciente)
                            .addComponent(jTFIDPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNumeroSUSPaciente)
                            .addComponent(jTFNumeroSUSPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLResponsavelPaciente)
                            .addComponent(jTFResponsavelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNomePaciente)
                            .addComponent(jTFNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCPFPaciente)
                            .addComponent(jTFCPFPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLRGPaciente)
                    .addComponent(jTFRGPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPCadastroPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrarPaciente)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jLCadastrodoPaciente.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLCadastrodoPaciente.setText("Cadastro do Paciente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPCadastroPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLCadastrodoPaciente)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCadastrodoPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPCadastroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarPacienteActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String NomePaciente = this.jTFNomePaciente.getText();
        Date DataNascimentoPaciente = new Date();
        try {
            DataNascimentoPaciente = sdf.parse(this.jTFDatadeNascimentoPaciente.getText());
        } catch (ParseException ex) {
            Logger.getLogger(JFPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
        String CPFPaciente = this.jTFCPFPaciente.getText();
        String RGPaciente = this.jTFRGPaciente.getText();
        String EnderecoPaciente = this.jTFEnderecoPaciente.getText();
        String TelefonePaciente = this.jTFTelefonePaciente.getText();
        String EstadoCivilPaciente = this.jTFEstadoCivilPaciente.getText();
        char SexoPaciente = this.jTFSexoPaciente.getText().toUpperCase().charAt(0);
        int IDPaciente = Integer.parseInt(this.jTFIDPaciente.getText());
        int NumeroSUS = Integer.parseInt(this.jTFNumeroSUSPaciente.getText());
        p = new Paciente(IDPaciente, NumeroSUS, p, NomePaciente, CPFPaciente, RGPaciente, EnderecoPaciente, TelefonePaciente, EstadoCivilPaciente, DataNascimentoPaciente, SexoPaciente);
        SPaciente.getInstance().getPacientes().add(p);
    }//GEN-LAST:event_jBCadastrarPacienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for (Paciente p : SPaciente.getInstance().getPacientes()) {
            JOptionPane.showMessageDialog(this, p.toString());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jBCadastrarPaciente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLCPFPaciente;
    private javax.swing.JLabel jLCadastrodoPaciente;
    private javax.swing.JLabel jLDatadeNascimentoPaciente;
    private javax.swing.JLabel jLEnderecoPaciente;
    private javax.swing.JLabel jLEstadoCivilPaciente;
    private javax.swing.JLabel jLIDPaciente;
    private javax.swing.JLabel jLNomePaciente;
    private javax.swing.JLabel jLNumeroSUSPaciente;
    private javax.swing.JLabel jLRGPaciente;
    private javax.swing.JLabel jLResponsavelPaciente;
    private javax.swing.JLabel jLSexoPaciente;
    private javax.swing.JLabel jLTelefonePaciente;
    private javax.swing.JPanel jPCadastroPaciente;
    private javax.swing.JTextField jTFCPFPaciente;
    private javax.swing.JTextField jTFDatadeNascimentoPaciente;
    private javax.swing.JTextField jTFEnderecoPaciente;
    private javax.swing.JTextField jTFEstadoCivilPaciente;
    private javax.swing.JTextField jTFIDPaciente;
    private javax.swing.JTextField jTFNomePaciente;
    private javax.swing.JTextField jTFNumeroSUSPaciente;
    private javax.swing.JTextField jTFRGPaciente;
    private javax.swing.JTextField jTFResponsavelPaciente;
    private javax.swing.JTextField jTFSexoPaciente;
    private javax.swing.JTextField jTFTelefonePaciente;
    // End of variables declaration//GEN-END:variables
}
