/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gabriel.interfaces;

/**
 *
 * @author SATC
 */
public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPaginaPrincipal = new javax.swing.JPanel();
        jBCadastrarPaciente = new javax.swing.JButton();
        jBCadastrarTriagem = new javax.swing.JButton();
        jBCadastrarEnfermeira = new javax.swing.JButton();
        jBCadastrarMedico = new javax.swing.JButton();
        jLPaginaPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPPaginaPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBCadastrarPaciente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBCadastrarPaciente.setText("Cadastrar Paciente");
        jBCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarPacienteActionPerformed(evt);
            }
        });

        jBCadastrarTriagem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBCadastrarTriagem.setText("Cadastrar Triagem");
        jBCadastrarTriagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarTriagemActionPerformed(evt);
            }
        });

        jBCadastrarEnfermeira.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBCadastrarEnfermeira.setText("Cadastrar Enfermeira");
        jBCadastrarEnfermeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarEnfermeiraActionPerformed(evt);
            }
        });

        jBCadastrarMedico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jBCadastrarMedico.setText("Cadastrar Médico");
        jBCadastrarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarMedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPPaginaPrincipalLayout = new javax.swing.GroupLayout(jPPaginaPrincipal);
        jPPaginaPrincipal.setLayout(jPPaginaPrincipalLayout);
        jPPaginaPrincipalLayout.setHorizontalGroup(
            jPPaginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPaginaPrincipalLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPPaginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCadastrarTriagem, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCadastrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addGroup(jPPaginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCadastrarMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCadastrarEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPPaginaPrincipalLayout.setVerticalGroup(
            jPPaginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPaginaPrincipalLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPPaginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrarPaciente)
                    .addComponent(jBCadastrarMedico))
                .addGap(47, 47, 47)
                .addGroup(jPPaginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrarTriagem)
                    .addComponent(jBCadastrarEnfermeira))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLPaginaPrincipal.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLPaginaPrincipal.setText("Página Principal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPPaginaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLPaginaPrincipal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLPaginaPrincipal)
                .addGap(18, 18, 18)
                .addComponent(jPPaginaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarPacienteActionPerformed
        new JFPaciente().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCadastrarPacienteActionPerformed

    private void jBCadastrarTriagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarTriagemActionPerformed
        new JFTriagem().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCadastrarTriagemActionPerformed

    private void jBCadastrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarMedicoActionPerformed
        new JFMedico().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCadastrarMedicoActionPerformed

    private void jBCadastrarEnfermeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarEnfermeiraActionPerformed
        new JFEnfermeira().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCadastrarEnfermeiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrarEnfermeira;
    private javax.swing.JButton jBCadastrarMedico;
    private javax.swing.JButton jBCadastrarPaciente;
    private javax.swing.JButton jBCadastrarTriagem;
    private javax.swing.JLabel jLPaginaPrincipal;
    private javax.swing.JPanel jPPaginaPrincipal;
    // End of variables declaration//GEN-END:variables
}
